CMake: add missing include after 8e69d663fa30
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: /man1/wl-mirror.1
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: share/man/man1/wl-mirror.1.gz